### ISSUE TITLE
How to migrate from the official postgres docker image?

### ISSUE THREAD

**Issue by einverne** [fengkx/postgres-docker#1]
I've already used the official postgres:lastest image for quite a while, then I found the problem with the Chinese search, I mapped the postgresql data to a named volume.

```
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - miniflux-db:/var/lib/postgresql/data
```

So I have a question, can I just replace the postgres image with this image. Or I should export all the data and then start up a new container with the image then reimport all data?
